

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sqlite-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: restaurant-backend-deployment
#   labels:
#     app: restaurant-backend
# spec:
#   replicas: 1 # مقصودة 1 وليست أكثر لأننا نستخدم SQLite كقاعدة بيانات محلية لا تدعم الكتابة المتزامنة من عدة Pods. في بيئة العمل الحقيقية سنستخدم PostgreSQL ونرفع الـ replicas.
#   selector:
#     matchLabels:
#       app: restaurant-backend
#   template:
#     metadata:
#       labels:
#         app: restaurant-backend
#     spec:
#       containers:
#       - name: backend-container
#         image: docker.io/rebal1sh/restaurant-backend:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 3005
#         env:
#         - name: NODE_ENV
#           value: "production"
#         - name: PORT
#           value: "3005"
#         # قمنا بتوجيه مسار قاعدة البيانات للمجلد المحمي لضمان عدم ضياع البيانات عند إعادة التشغيل
#         - name: DATABASE_URL
#           value: "file:/app/data/dev.db" 
#         - name: ADMIN_USERNAME
#           value: "admin"
#         - name: ADMIN_PASSWORD
#           value: "SuperSecretAdminPassword2026"
#         - name: JWT_SECRET
#           value: "your_ultra_secure_jwt_secret_key_here"
#         - name: EMAIL_HOST
#           value: "smtp.gmail.com"
#         - name: EMAIL_PORT
#           value: "587"
#         - name: EMAIL_SECURE
#           value: "false"
#         - name: EMAIL_USER
#           value: "mhd.mosrafa@gmail.com"
#         - name: EMAIL_PASS
#           value: "lcsdqwomvsvvrwel"
#         - name: BASE_URL
#           value: "http://localhost:3005"
#         volumeMounts:
#         - name: sqlite-storage
#           mountPath: /app/data
#       volumes:
#       - name: sqlite-storage
#         persistentVolumeClaim:
#           claimName: sqlite-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
# spec:
#   type: LoadBalancer
#   selector:
#     app: restaurant-backend
#   ports:
#     - protocol: TCP
#       port: 3005
#       targetPort: 3005




apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend-deployment
  labels:
    app: restaurant-backend
spec:
  replicas: 1 # مقصودة 1 وليست أكثر لأننا نستخدم SQLite كقاعدة بيانات محلية لا تدعم الكتابة المتزامنة من عدة Pods. في بيئة العمل الحقيقية سنستخدم PostgreSQL ونرفع الـ replicas.
  selector:
    matchLabels:
      app: restaurant-backend
  template:
    metadata:
      labels:
        app: restaurant-backend
    spec:
      containers:
      - name: backend-container
        image: docker.io/rebal1sh/restaurant-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3005"
        # قمنا بتوجيه مسار قاعدة البيانات للمجلد المحمي لضمان عدم ضياع البيانات عند إعادة التشغيل
        - name: DATABASE_URL
          value: "file:/app/data/dev.db" 
        - name: ADMIN_USERNAME
          value: "admin"
        
        # استدعاء كلمة السر من ملف الـ Secrets
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ADMIN_PASSWORD
              
        # استدعاء مفتاح التشفير من ملف الـ Secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
              
        - name: EMAIL_HOST
          value: "smtp.gmail.com"
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_SECURE
          value: "false"
        - name: EMAIL_USER
          value: "mhd.mosrafa@gmail.com"
          
        # استدعاء كلمة سر الإيميل من ملف الـ Secrets
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: EMAIL_PASS
              
        - name: BASE_URL
          value: "http://localhost:3005"
        volumeMounts:
        - name: sqlite-storage
          mountPath: /app/data
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: restaurant-backend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005