apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-frontend-deployment
  labels:
    app: restaurant-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-frontend
  template:
    metadata:
      labels:
        app: restaurant-frontend
    spec:
      containers:
      - name: frontend-container
        image: docker.io/rebal1sh/restaurant-frontend:latest # صورتك المرفوعة للفرونت
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-frontend-service
spec:
  type: LoadBalancer # لفتح الفرونت إيند على المتصفح عبر localhost:80
  selector:
    app: restaurant-frontend
  ports:
    - protocol: TCP
      port: 80         # بورت المتصفح الخارجي
      targetPort: 80   # بورت Nginx الداخلي المفتوح بالـ Dockerfile