apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  ADMIN_PASSWORD: "SuperSecretAdminPassword2026"
  JWT_SECRET: "your_ultra_secure_jwt_secret_key_here"
  EMAIL_PASS: "lcsdqwomvsvvrwel"